# Generated by Django 3.2.25 on 2024-06-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('employee', 'menu')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_value',
        ),
    ]
